### ISSUE TITLE
关于中文书名，正式征集网友意见

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/CSS-Secrets#19]
为大致了解读者对中文书名的偏好，我在微博发起了[一项投票](http://vote.weibo.com/poll/136170170)。截至 11 月 15 日，各候选方案的得票情况如下：

| 备选书名 | 得票情况 |
| --- | --: |
| 《鲜为人知的 CSS》 | 17 (3.5%) |
| 《CSS 秘密花园》 | **170 (34.6%)** |
| 《CSS 探秘》 | 59 (12%) |
| 《CSS 的 47 个秘密》 | 19 (3.9%) |
| 《CSS 秘籍》 | 31 (6.3%) |
| 《你不知道的 CSS》 | 34 (6.9%) |
| 《CSS Secrets 中文版》 | 63 (12.8%) |
| 《CSS 一姐写的、魔法哥翻译的那本书》 | 98 (20%) |

同时，网友们也提出了一些不错的备选书名，比如：
- 《CSS 奥秘》或《CSS 奥秘书》
- 《CSS 秘境》
- 《CSS 秘语》
- 《CSS 解密》
- 《CSS 揭秘》
- 《CSS 秘方》
- 等等

本书的最终中文名将由出版社决定，但我相信网友的意见将是非常重要的参考因素。目前中文书名还未定稿，大家请在这里发表观点，谢谢！

---

最好说出你的观点，而不是简单地投票。

> 单纯的投票贴将在汇总后删除：
> - @wileam @GuanyuChen 赞成《CSS 奥秘》
> - @cforth @SuperKieran @iamcho 赞成《CSS 秘密花园》
> - @MangGoDio 赞成《CSS 解密》

**Comment by wileam** [comment]
CSS 奥秘 +1

**Comment by GuanyuChen** [comment]
CSS 奥秘 +2

**Comment by cforth** [comment]
《CSS 秘密花园》

**Comment by MangGoDio** [comment]
CSS 解密

**Comment by SuperKieran** [comment]
CSS 秘密花园

**Comment by hax** [comment]
我提了“CSS 奥秘书”这个建议。

讲讲我的想法。

## 

在投票选项中，排名第二的“CSS 一姐写的、魔法哥翻译的那本书”虽然是个很有趣味的名字，我也挺喜欢，但是作为正式名字有点过于不严肃（dou bi），太长也不利于传播，另外理论上也缺乏唯一性（CSS不止一姐，她们也能再有新书，魔法哥也可能再翻译那些新书）。我猜想投票给这个名字的人大多数是出于好玩。

排名第三的是“CSS Secrets 中文版”，XX中文版固然很清楚，~~但是作为正式名字的我真的没见过，出版社恐怕也不会答应~~（见后 https://github.com/cssmagic/CSS-Secrets/issues/19#issuecomment-156971252 ）。

## 

下面说说排名第一的“CSS 秘密花园”。

这个名字可能是大漠（@airen）在介绍这本书时首先使用的名字。这个名字听上去挺文艺的，且让我们联想到三本有一定名气的书：十年前出版的《[CSS 禅意花园](http://book.douban.com/subject/2052176/)》（The Zen of CSS Design），最近的电子书《[JavaScript 秘密花园](http://bonsaiden.github.io/JavaScript-Garden/zh/)》（JavaScript Garden），以及最近的畅销涂色书《[秘密花园](https://book.douban.com/subject/26376603/)》（Secret Garden）。

我个人对这个名字不是特别中意，原因如下：
1. CSS Secrets 的原书名里并不包含 garden 这个词。（Zen 那本书的网站原名是 Zen Garden。）
2. “CSS 秘密花园”这个名字过于接近非技术畅销书《秘密花园》。
3. “秘密花园”听上去过于文艺，而 CSS Secrets 其实还是偏技术而不是设计的。（相反 Zen Garden 确实是偏设计的。）
4. JS Garden 那本电子书我个人评价一般。Zen 那本书有特色，但是综合评价也不高。而 CSS Secrets 目前在 Amazon 上评价高达 4.8 。书名上靠近这两本相对一般的书可能不是好的选择。

## 

“你不知道的 CSS”和“鲜为人知的 CSS”是比较相似的两个名字，前者令我们想到同样由图灵引进的《你不知道的JavaScript》（You Don't Know JS）系列。除非真的打算再凑些其他的（你不知道的HTML？你不知道的PHP？），相似未必是好事。而且同名系列（如21天学XXX，或Head first系列）通常给人印象是入门书（pian qian）。

BTW，实际上我不喜欢“You Don't Know XXX”这样标题党的名字，虽然《You Don't Know JS》确实是不错的。

## 

我考虑过“CSS 秘籍”或者“CSS 秘笈”。这些名字让我联想到“武功秘笈”或“美容小秘笈”。我最后还是觉得不满意，小家子气，不够洋气（tu qi），有 cheap 感（类似“XX宝典”）。

## 

最后我想到的名字就是《CSS 奥秘书》。
- 符合原书名
- 符合原书不仅是讲一个技巧而且讲整个原理思路的特点（探索奥秘，而不是仅仅给出秘技）
- “奥秘”是可以探索和理解的（如“探索科学的奥秘”），而不会过于神秘主义（反例如“秘术”、“奥术”、“奥义”、“秘境”、“秘语”等）

之所以在“奥秘”后面加上“书”，是觉得更顺口，且更能凸显这本书的地位。像“犀牛书”、“白皮书”、“红宝书”……

## 

以上。

**Comment by Ovilia** [comment]
把一姐看成一丝姐的只有我吗…… @yisibl

**Comment by myst729** [comment]
奥秘是我提的，+1。
秘境也是我提的，这个属于说出来就后悔那种，-1。

**Comment by airen** [comment]
贺佬 (@hax) 讲解的很透彻。我当初取这个名主要出于好记，顺口。我的理解是这样的，《CSS秘密花园》来于《JS秘密花园》。目前 CSS Secrets 这本书，里面介绍的一些技巧（我理解成技巧）的集锦。而这些技巧，大家平时或多或少有接触或者说在使用，但知道的人并不太多，这也就是我称之为秘密的初意。后面加上一个花园，主要是觉得他们是集锦，故用花园（文艺青年范？）

另外书取什么样的名，其实对于畅不畅销还是很重要的，内行看门道，外行看行头。有一个好听、好记的名是较为重要的（我当初为《图解CSS3》一书取名，也费时很久）。当然书的内容质量是口碑。

**Comment by cssmagic** [comment]
@hax 
顺便说一句，采用《×××中文版》作为书名的案例还是有的，比如：
- [《CSS Cookbook 中文版》](http://www.oreilly.com.cn/index.php?func=book&isbn=978-7-121-04947-7) 以及 O'Reilly 的其它 cookbook。
- [《Designing Interfaces 中文版》](http://www.oreilly.com.cn/index.php?func=book&isbn=978-7-121-04797-8)

不过对于这本书，我还是希望有个真正的中文名。

**Comment by hax** [comment]
@cssmagic 
嗯，是我想当然了。

Cookbook系列似乎全都翻译为“XX cookbook 中文版”。
还有 Effective XXX 系列。

感觉上直接用XXX中文版的不少是只有两个单词的名字（一个是技术名，一个是一个比较基础的单词）。以此来说，CSS Secrets 倒是也符合的。

其他特例还有
- Restful Web APIs 中文版
- C++ Templates 中文版

（因为每个单词都不用/没法翻译）

**Comment by iamcho** [comment]
CSS 秘密花园

**Comment by Justineo** [comment]
我一开始就建议用「奥秘」，因为从样章来看书内容包含了一些读者不知道的技巧和 CSS 甚至程序设计的精妙思想。前者可称为「秘技」，后者可称「奥义」。其次这个词和其他名字有一定的区分度，不会被当成系列的一部或是借其他书籍之名的营销。一本经典的书，我觉得应该有一个大气不落俗套的名字。

所以我建议用《CSS 奥秘》。

**Comment by Justineo** [comment]
@Ovilia +1

**Comment by yisibl** [comment]
@Ovilia :bomb:  :boom:

**Comment by cssmagic** [comment]
聊一下我对书名翻译的看法。

拿到这本书后对中文书名的第一想法，其实是《CSS 魔法书》。我觉得很贴切，而且易传播，但细想之后，感觉这会引起诸多误解，于是放弃。（这个书名还是留给我自己写的 CSS 书吧！）

后来看到大漠 (@airen) 在 W3Cplus 网站上采用了《CSS 秘密花园》这个名字，感觉倒是不错。我能体会到其中的两个梗：
- 《CSS 禅意花园》：这是一书挺有名的 CSS 书。（我其实对这本书不是那么推崇，但它在国内的口碑却奇好，所以即使把两者相提并论，也可以接受。）
- 《秘密花园》：全球畅销的涂色书，有一定的解谜成分。（容易被认为是借势营销，但也利于传播。）

这个名字有一些文艺气息，跟原书的玫红色色调也挺搭的。所以总体来说，如果最终书名是这个，我可以接受，不遗憾。

再后来就是贺老 (@hax)、顾兄 (@Justineo)、粽兄 (@myst729) 三人不约而同提出的 “奥秘” 一词。我一开始没想到这个词，因为我感觉这个词似乎跟原书的 “secret” 所指的并不是一回事。但上面顾兄的解读又让我觉得很合理，而且这个词确实要更加大气、有份量。

所以我目前最为推崇的中文书名是《CSS 奥秘书》。

**Comment by ziven27** [comment]
我觉得就叫《css的秘密》就好了啊，和《维多利亚的秘密》不是很像。
通俗易懂，也给人亲切的感觉。

**Comment by cssmagic** [comment]
出版社最终定名《CSS 揭秘》…… :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by hax** [comment]
揭秘 = expose/break secrets 
意思倒也马马虎虎可以对上。

只是这名字总感觉不够正气，跟《CSS权威指南》这种名字一比就感觉局促。
