### ISSUE TITLE
征集书名副标题的中文翻译

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/CSS-Secrets#20]
这本书的全名叫作《CSS Secrets：Better solutions to everyday web design problems》。

现向热心网友征集副标题的中文翻译。

**Comment by cssmagic** [comment]
~~我自己胡乱想了两个：~~
- ~~用更好的方法解决网页样式难题~~
- ~~网页样式难题的终极答案~~

在深思熟虑之后，我在下面又提了一个新方案。

**Comment by voidove** [comment]
**CSS探秘：网页样式更优解**

个人比较喜欢中文书名“CSS探秘”。“探”字，有上下而求索的感觉。

**Comment by YIXUNFE** [comment]
提一个:

**更好地解决 CSS 问题**

接地气不? :joy:

**Comment by lupuxyz** [comment]
更好的网页设计日常疑难解答

**Comment by Justineo** [comment]
常见网页设计难题的更优解

**Comment by cz848** [comment]
样式难题解决之道

**Comment by CharisLee** [comment]
CSS揭秘：你所困扰的网页设计难题！

**Comment by hax** [comment]
CSS奥秘书：如何更好地解决web设计的日常问题

**Comment by richardo2016** [comment]
建议一个《CSS秘法》 
理由：简短，贴合原意( •̀ ω •́ )y

**Comment by elvinzhu** [comment]
css的那些事儿

**Comment by cssmagic** [comment]
新方案：
**重新解答网页设计中的经典难题**

better solutions → 更好的解决方案 → （以更好的解决方案）重新解答
everyday → 每天都会遇到的 → 经典的

因为这本书并不是重点探讨设计的，所以我在前两个方案中竭力避免出现 “设计” 这个字眼。但 “网页样式” 这个词并不是一个通用词汇，所以这个方案还是遵从原文了。

**Comment by cssmagic** [comment]
@richardo2016 
谢谢建议。不过你应该发到 [这里](https://github.com/cssmagic/CSS-Secrets/issues/19)。

**Comment by cssmagic** [comment]
出版社决定中文版名书不设置副标题。不过在封面上会采用 “重新解答网页设计中的经典难题” 作为书名的扩展标语。

**Comment by hanmingyang** [comment]
👍
