### ISSUE TITLE
[译] [003] 本书收到的赞誉

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/CSS-Secrets#21]
---

> 本文是早期译版，未经校审。仅供参考。

---
# Praise for _CSS Secrets_
# 本书收到的赞誉

This is a new generation of CSS books, for a new generation of CSS. No longer a simple language tied to complicated browser hacks and workarounds, CSS is now a richly powerful and deeply complex ecosystem of over 80 W3C specifications. Nobody is better at making sense of this new CSS, and of providing design principles that help you solve problems with it, than Lea Verou—among the handful of truly amazing coders I've known.

这本书是为新一代 CSS 所写的新一代 CSS 书籍。也许从前的 CSS 只会让你联想到浏览器里的各种小把戏，但如今 CSS 已经成为一门功能强大、具备完整生态、涉及 80 多项 W3C 规范的复杂语言。而在我所知的技术专家中，没人比 Lea Verou 更能领会新一代 CSS 的精髓，没人能像她那样透彻地给出问题解决之道。

Jeffrey Zeldman,
author, _Designing with Web Standards_

{--:}——Jeffrey Zeldman  
《网站重构》作者 

---

Lea Verou's encyclopaedic mind is one of a kind, but thanks to this generous book, you too can get an insight into what it's like to wield CSS to do just about anything you can think of. Even if you think you know CSS inside-out, I guarantee that there are still secrets in this book waiting to be revealed.

Lea Verou 那渊博的学识是无法复制的，但这本书的倾囊相授令我等凡人也有机会一窥 CSS 强大威力与神奇魔力。即使你认为自己对 CSS 已经了如指掌，我保证这本书仍然会让你大开眼界。

Jeremy Keith,
Shepherd of Unknown Futures, Clearleft

{--:}——Jeremy Keith  
《JavaScript DOM 编程艺术》作者

---

If you want the inside scoop on fascinating CSS techniques, smart best practices, and some flat-out brilliance, don't hesitate—read this book. I loved it!

如果你想深入探寻 CSS 的美妙之处、创意之处与智慧之处，那就别犹豫了——赶快翻开这本书吧。它让我爱不释手！

Eric A. Meyer

{--:}——Eric A. Meyer  
《CSS 权威指南》作者

---

Lea is an exceedingly clever coder. This book is absolutely packed with clever and useful ideas, even for people who know CSS well. Even better, you'll feel more clever in your work as this book encourages pushing beyond the obvious.

Lea 是一位极其智慧的编码人。这本书蕴含了无穷的智慧与创意，即使你已是 CSS 高手，也仍将从中获益。更重要的是，这本书还将长久激发你的智慧，因为它已传授给你突破平庸的信念。

Chris Coyier,
CodePen

{--:}——Chris Coyier  
CodePen 创始人

---

_CSS Secrets_ is an instant classic—so many wonderful tips and tricks you can use right away to enhance your UX designs!

《{$BOOK_NAME$}》就是一部现成的经典——它汇集了众多精彩绝伦的技巧，能够立即改善你的网页体验！

Christopher Schmitt,
author of _CSS Cookbook_

{--:}——Christopher Schmitt  
《CSS Cookbook》作者

---

There aren't many books that provide as many practical techniques as Lea Verou's _CSS Secrets_. Filled with dozens of solutions to common design problems, the book is a truly valuable collection of smart tips and tricks for getting things done well, and fast. Worth reading, even if you think that you know the ins and outs of CSS!

极少有哪本书能像 Lea Verou 的这本《{$BOOK_NAME$}》一样囊括如此之多的实用技巧。它针对常见的网页设计难题提出了数不胜数的解决方案，手到擒来，高效可靠，堪称 CSS 智慧与技巧的集大成之作。哪怕你自认是 CSS 领域的专家，这本书仍然值得一读！

Vitaly Friedman,
cofounder and editor-in-chief of Smashing Magazine

{--:}——Vitaly Friedman  
《Smashing Magazine》联合创始人兼总编

---

Without fail, whenever I read something written by Lea Verou, I manage to learn something new. _CSS Secrets_ is no different. The book is broken down into easy-to-digest chunks filled with lots of juicy bits of knowledge. While some of the book is very forward looking, there is plenty that I’ve been able to take away and apply to my own projects right away.

每当我读到 Lea Verou 的文章时，总能收获新技能。这本《{$BOOK_NAME$}》也不例外。这本书经过了精心编排，它把丰富的经验和技巧分解为一篇篇的短文，易读易懂。尽管书中的部分内容颇具前瞻性，但大多数知识还是极为实用的，我一直在自己的项目中现学现用。

Jonathan Snook,
web designer and developer

{--:}——Jonathan Snook  
网页设计师兼开发者

---

Lea's book is fantastic. She bends and contorts CSS to do things I'm pretty sure even the spec authors never imagined! You will learn multiple ways of accomplishing each graphic effect by trying out the techniques she walks through in each chapter. Later, in your work, you'll find yourself saying, "hmm, that thing Lea did will work perfectly here!" Before you know it, your site is almost image free because your graphics are all in easy to maintain CSS components. What's more, her techniques are fun, walking the line between practical and improbable!

Lea 的这本书棒极了。她对 CSS 运用已臻化境，她创造的各种神奇效果我敢说即便是规范作者也无法想像！这本书的每个章节都各具特色，呈现了各式各样的技巧，它将教会你用多种思路来达成各式各样的设计效果。不久之后，你在工作中就会不由自主地念念有词：“嗯，这个效果可以用 Lea 的方法来完美实现！” 甚至在不知不觉之中，你的网站都不怎么需要用到图片了，因为你已经把所有图形效果都写成了易于维护的 CSS 组件。最重要的是，她的表达方式生动活泼，注重实效但又不失奇趣！

Nicole Sullivan,
Principal Software Engineer, creator of OOCSS

{--:}——Nicole Sullivan  
资深软件工程师、OOCSS 项目创始人

---

Lea Verou's _CSS Secrets_ is useful not so much as a collection of CSS tips, but as a textbook on how to solve problems with CSS. Her in-depth explanation of the thought process behind each secret will teach you how to create your own solutions to CSS problems. And don't miss the Introduction, which contains some must-read CSS best practices.

Lea Verou 的这本《{$BOOK_NAME$}》不只是一套 CSS 技巧的合集，而更是一本注重实效的 CSS 经典教科书。在每篇攻略中，她不仅讲授解决问题的方法，更会深入解析背后的思路，从而教会你如何自行探索更多的 CSS 奥秘。千万不要错过第一章引言，那里有你不可不知的 CSS 最佳实践。

Elika J. Etemad (aka fantasai),
W3C CSS Working Group Invited Expert

{--:}——Elika J. Etemad（网名 fantasai）  
W3C CSS 工作组特邀专家

---

Lea’s presentations have long been must-see events at web development conferences around the world. A distillation of her years of experience, _CSS Secrets_ provides elegant solutions for thorny web design issues, while also—and more importantly—showing how to solve problems in CSS. It's an absolute must-read for every frontend designer and developer.

Lea 在全球各地的技术会议上所作的演讲早已成为不可错过的学习素材。作为她多年经验的提练与升华，这本《{$BOOK_NAME$}》为各种网页设计顽症提供了优雅的解决方案，而且更重要的是，这本书展示了 CSS 解决问题的方式和思路。这绝对是每位前端设计师和开发者必读的一本书。

Dudley Storey,
designer, developer, writer, web education specialist

{--:}——Dudley Storey  
设计师、开发者、作家、Web 教育专家

---

I thought I had a pretty advanced understanding of CSS, then I read Lea Verou's book. If you want to take your CSS knowledge to the next level, this is a must-own.

我一直以为我对 CSS 的理解已经达到相当高的层次了，直到我读到了 Lea Verou 的这本书。如果你希望把自己的 CSS 技能提升到一个新的段位，那这本书正是不二之选。

Ryan Seddon,
Team Lead, Zendesk

{--:}——Ryan Seddon  
Zendesk 团队负责人

---

_CSS Secrets_ is by far the most technical book that I have ever read on the topic. Lea has managed to push the boundaries of a language as simple as CSS so far that you will not be able to distinguish this from magic. Definitely not a beginner's read; it's heavily recommended to anyone thinking they know CSS all too well.

《{$BOOK_NAME$}》是迄今为止我在这个领域里读到的最具专业性的书籍。或许你曾以为 CSS 这门语言简单无奇，但 Lea 已将它的疆域拓展为如此广袤的一片天地，令人叹为观止、惊为幻术。这本书显然不适合初学者；但我会强烈推荐给每一位自信精通 CSS 的开发者。

Hugo Giraudel,
frontend developer, Edenspiekermann

{--:}——Hugo Giraudel  
前端开发者、Edenspiekermann 公司工程师

---

I often think that CSS can seem a bit like magic: a few rules can transform your web pages from blah to beautiful. In _CSS Secrets_, Lea takes the magic to a whole new level. She is a master magician of CSS, and we get to explore that magical world along with her. I can’t count how many times I said out loud while reading this book, “That’s so cool!” The only trouble with _CSS Secrets_ is that after reading it, I want to stop everything else I’m doing and play with CSS all day.

我一直觉得 CSS 就像是一种魔法：寥寥数行的代码就可以让你的网页脱胎换骨、焕然一新。而在《{$BOOK_NAME$}》这本书中，Lea 将这种魔法提升到了一个全新的境界。她就像是一位 CSS 魔法大师，带领我们在这个充满魔力的世界里自由翱翔。在阅读这本书的过程中，我曾无数次地脱口而出——“这简直帅呆了！” 这本书唯一的问题在于，在读完它之后，我已对其它事情兴趣全无，终日沉溺在 CSS 的魔幻之中无法自拔。

Elisabeth Robson,
cofounder of WickedlySmart.com and coauthor of _Head First JavaScript Programming_

{--:}——Elisabeth Robson  
WickedlySmart.com 联合创始人、《Head First JavaScript Programming》联合作者

---

_CSS Secrets_ is a book that all web developers should have in their library. Using the information it contains you'll learn numerous hints and tips to make CSS perform tasks you never thought possible. I was astonished at how often the author came up with simple and elegant lateral thinking solutions to problems that had bugged me for years.

《{$BOOK_NAME$}》值得被每一位网页开发者收入囊中。这本书将传授给你丰富的经验和技巧，帮助你实现那些你原以为不可能用 CSS 完成的任务。最令我惊讶不已的是，对于每一个困扰我多年的网页样式难题，作者居然都可以从不同的角度提出不止一种简洁优雅的解决方案。

Robin Nixon,
web developer, online instructor, and author of several books on CSS

{--:}——Robin Nixon  
网页开发者、在线讲师、多本 CSS 书籍的作者

---

As a master designer and programmer, Lea Verou's book is as beautiful and as well thought out as her code. Whether you're fairly new to CSS, or well versed in the intricacies of CSS3, this book has something for everyone.

Lea Verou 是一位网页设计和开发领域的大师，而她的书跟她的代码一样富有美感、饱含智慧。不论你对 CSS 是否精通，也不论你对 CSS3 的种种细节是否了解，这本书总有适合你的地方。

Estelle Weyl,
Open Web Evangelist and coauthor of _CSS: The Definitive Guide_

{--:}——Estelle Weyl  
开放 Web 布道师、《CSS 权威指南》联合作者

**Comment by hanmingyang** [comment]
马上到12月份了，电子版还是没看到

**Comment by yanhaijing** [comment]
坐等纸质版了

**Comment by cssmagic** [comment]
@hanmingyang @yanhaijing 
嗯，快了，快了…… :sweat_smile:

**Comment by yanhaijing** [comment]
@cssmagic 买首发

**Comment by yujiayinshi** [comment]
后面的书名都成《{$BOOK_NAME$}》了，是不是markdown语法出问题了。

**Comment by cssmagic** [comment]
@yujiayinshi 
提交译稿时中文书名还没有定，于是用了占位符代替。
