### ISSUE TITLE
关于 “specificity” 一词的译法

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/CSS-Secrets#3]
现有的主要译法如下：
- 最精确的应该是 “特异性”（或 “特殊性”），但流传度似乎不高，跟它的工作原理的映射度也不高，不直观；
- “优先级” 在非正式场合（博客、原创图书、口头表述等）使用最多，易理解，但不够精确严谨；
- 综合起来，“权重” 似乎是一个各方面比较均衡的译法，但其实跟 “优先级” 这个译法也差不多。

由于目前在书中还没有遇到这个词，我也没有做最终决定，暂时先采用了我印象中最流行的 “优先级” 这个译法写入表中。

---

本讨论源自： https://github.com/cssmagic/CSS-Secrets/issues/1#issuecomment-131716872

**Comment by getive** [comment]
还是 “特异性”（或 “特殊性”）好。优先级在CSS中另有所指，是两个概念。

**Comment by Justineo** [comment]
个人感觉「优先级」是有一定歧义的，样式来源的「层叠顺序」（Cascading Order）和选择器的 specificity 都可以算是某种「优先级」。多数初学者分不清这些优先级的差异。当然如果区分为「样式来源优先级」和「选择器优先级」应该也可以接受。单独出现时建议带上「选择器」。如果用「特异性」这个词，可能会有一些理解的成本，因为毕竟使用不是太广泛。但是看书就是来学习的不是么 :smile:

**Comment by cssmagic** [comment]
@Justineo 完全同意上述评论。

其中：

> 当然如果区分为「样式来源优先级」和「选择器优先级」应该也可以接受。单独出现时建议带上「选择器」。

目前表中确实已注明 “（选择符的）优先级”。当然目前表中所列并不是最终选择。开 issue 就是让大家来讨论的。 :smile:

**Comment by Gxsghsn** [comment]
选择符的优先级 可以接受没有歧义

**Comment by xxjinwei** [comment]
“权重”更能表现可计算性

**Comment by hax** [comment]
我找到了我许多年前考虑过的想法（http://hax.iteye.com/blog/114914 ）：

> Specificity译作“特殊性”，有点不适应，因为中文习惯里没有比较两个事物的特殊性的用法。可译作“专指度”。其他译法包括“专指性”、“特异度”等。

**Comment by yisibl** [comment]
我倾向于「权重」。

**Comment by hax** [comment]
@yisibl 「权重」直接对应于“weight”。所以跟“优先级”的译法差不多，都没有体现原词“specificity”的内涵。

**Comment by Justineo** [comment]
总的来看「特异性」可能是最贴切的。就看是想普及准确的译名，还是用更接地气的译法让人一下就能理解。

说个我在游戏汉化中看到的案例：

> DotA 中有一个英雄的英文名称叫做「Juggernaut」，由于用了 War3 中剑圣的模型所以汉化版一直译为「剑圣」。直到有一个版本中，汉化组决定纠正所有不贴切的翻译，重新译为「主宰」，并且同时修改了好几个类似英雄的名字。这下可好，被广大玩家喷惨了。很多人说我们都习惯说剑圣了，你给我改了以后交流起来好麻烦，还要跟新人介绍剑圣和主宰其实是同一个意思。但汉化组不为所动，坚持把更贴切的更符合英语原文意思的译名发布了出来。

我想说的是 specificity 这个词可能也属于「主流译法并不贴切」的情况，选哪种都难两全。最后怎么选择，更多在于译者想传达的自己的想法。

**Comment by hax** [comment]
通过google查询确定使用频度如下：

| 译法 | 结果条数 |
| --- | --- |
| 优先级 | 11000+ 3000+ |
| 优先权 | 3000+ 1000+ |
| 权重 | 6000+ 1000+ |
| 特殊性 | 4000+  300+ |
| 特异性/特异度 | 8000+ 900+ |
| 特指度 | 100+ |
| 专指性/专指度 | < 10 |

查询方式是用 "css" "specificity" "{译名}"，以及 ''css{译名}" "specificity"。

就这个结果来说，并没有哪一种译法有数量级上的优势，即使在前端这个小群体里也没有达到“约定俗成”的地位。因此我认为仍然可以重新确定译名。

我个人建议“专指度”或“特异度”。

**Comment by yanxyz** [comment]
我选择"权重“，MDN 与 css-tricks 都是直接说它们是 weight.

**Comment by hax** [comment]
@yanxyz 给下链接看看？

**Comment by yanxyz** [comment]
@hax google "css specificity weight" 可以看到一些页面。当然这样直接说 “specificity" 是 ”weight" 不多。我个人倾向 "权重“。

**Comment by AndorChen** [comment]
我目前也在翻译一本 CSS 书，参照李松峰老师翻译的《[CSS设计指南](http://www.ituring.com.cn/book/1111)》，我把 specificity 译为“特指度”。

术语翻译最难，无论怎么翻译都会“得罪”一批人，这时应该遵循“约定俗成”原则，看以往著作的翻译，以及社区的接受程度。大家统一之后，提到那个译法，自然就能对应到某件事情（原理，处理方式等）。“鲁棒性”广受诟病，但是提到这个词几乎都知道对应的是 Robustness——这就达到了约定俗成。

**Comment by hax** [comment]
松峰老师这个译法跟“特异度”或“专指度”类似，倒是可以考虑。cc @cncuckoo
