### ISSUE TITLE
提交勘误

### ISSUE THREAD

**Issue by keyfoxth** [cssmagic/CSS-Secrets#39]
### 第 169 页的 JS 代码第 5 行

> `slider.insertBefore(img, div);`

正确的写法应该是 `slider.insertBefore(div, img);`。

---

这个错误已存在于英文原书的[待确认的勘误表](http://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920031123)，不过这确实是个错误。

**Comment by cssmagic** [comment]
谢谢反馈，稍后会回复的。 😃

**Comment by cssmagic** [comment]
已收入 [“勘误表”](https://github.com/cssmagic/CSS-Secrets/issues/2) 👍
