### ISSUE TITLE
提交勘误 - 印刷颜色不对

### ISSUE THREAD

**Issue by ghost** [cssmagic/CSS-Secrets#40]
### 第 115 页 · `<dd>`印刷颜色不对

> ```
> <dl>
>     <dt>Name: </dt>
>     <dd>Lea Verou</dd>
>     <dt>Email: </dt>
>     <dd>lea@verou.me</dd>
>     <dt>Location: </dt>
>     <dd>Earth</dd>
> </dl>
> ```

`lea@verou.me` 前面的 `<dd>`应该为印刷为绿色，而实际是黑色
`
（贡献者： @hdming）

**Comment by cssmagic** [comment]
谢谢反馈，已收入 [“勘误表 - 排版失误”](https://github.com/cssmagic/CSS-Secrets/issues/36) 👍
