### ISSUE TITLE
“实色”改为“纯色”

### ISSUE THREAD

**Issue by AndorChen** [cssmagic/CSS-Secrets#41]
书中多处出现了“实色”这种表述，我的第一反应是，难道还有“虚色”？

书中所说的“实色”，英文是 solid color，经查：

![1323213431](https://cloud.githubusercontent.com/assets/436680/15278556/e3d240f0-1b4c-11e6-863f-87a6587daa62.jpg)

《现代汉语词典（汉英双语）》

“实”字的第一个义项是指“实心”，对应的英文也是 solid，但是 solid 还有一个义项（第 8 条）：

![587050461](https://cloud.githubusercontent.com/assets/436680/15278555/e3d1e01a-1b4c-11e6-87eb-93bf0a96453c.jpg)

《牛津高阶（第 8 版）》

可见，当指颜色时，应该是“纯色”。

从 CSS 的角度来理解，solid color 应该是与渐变色对应的，因此也应该是“纯色”。

**Comment by cssmagic** [comment]
我搜索了一下译稿中的所有 “实色”，并核对了原文：大部分原文是 “solid color”，少部分是我自己的表述选择。

把没有上下文的 “solid color” 一词译作 “实色” 或 “纯色”，我觉得都是合理的译法选择。但我应该不会选择 “单色”，因为读者极有可能会把它跟 “monochrome” 混淆起来。好，接下来看 “实色” 和 “纯色” 之间的取舍。

从我自己的感受来，“纯色” 可能引发歧义。色彩三要素在技术领域一般译作 “色相、饱和度、亮度”，但在美术领域一般称作 “色相、纯度、明度”。由于我自己是学画画的，所以本能地慎用 “纯色” 这一译法。

而 “实色” 的译法没有这些问题。而且我学画画的时候，涂满色的效果就是叫 “实色” 的。

> 书中多处出现了“实色”这种表述，我的第一反应是，难道还有“虚色”？

书中出现的 “solid color” 往往不仅是使用同一种颜色填充的效果，在绝大多数时候，其上下文还显示它**不具有半透明效果**。因此我选择的 “实色” 译法同时还暗示了透明度。也就是说，“实” 所对应的 “虚” 实际上是存在的，即半透明——这应该可以解答你的疑惑。

> “另外一种方法是：在图片的上层覆盖一层半透明的纯色；或者把图片设置为半透明并覆盖在一层实色背景之上……”
> 
> ——《CSS 揭秘》第 94 页 · 第一行

在这一句话中，当颜色具有半透明效果时，我译作 “纯色”；当颜色不具有透明效果时，我采用 “实色”。可见我是知道 “纯色” 译法的，并且我会有意识地选择最适宜读者理解的译法。 :smiley:
