### ISSUE TITLE
[提交勘误-65页-图3-28]

### ISSUE THREAD

**Issue by ArvinTung** [cssmagic/CSS-Secrets#42]
左右两侧的背景颜色反了，左边应为#655，右边应为#58a

**Comment by cssmagic** [comment]
谢谢反馈，会尽快确认的 😃

**Comment by cssmagic** [comment]
:+1: 已确认。

已添加到原书勘误。会尽快更新中文版勘误。

**Comment by cssmagic** [comment]
❤️ 已收入 [“中文版勘误表”](https://github.com/cssmagic/CSS-Secrets/issues/2)
