### ISSUE TITLE
《CSS 揭秘》 Page108 

### ISSUE THREAD

**Issue by peacelee** [cssmagic/CSS-Secrets#44]
坐标图 右边的公式(写反了)： 
错误：sinα = x/r cosα = y/r
正确：sinα = y/r cosα = x/r

**Comment by cssmagic** [comment]
👍 谢谢反馈，确认后会添加到勘误表中。

**Comment by cssmagic** [comment]
:+1: 已确认。

已添加到原书勘误。会尽快更新中文版勘误。

**Comment by cssmagic** [comment]
❤️ 已收入 [“中文版勘误表”](https://github.com/cssmagic/CSS-Secrets/issues/2)
