### ISSUE TITLE
提交勘误 - 颜色与印刷失误

### ISSUE THREAD

**Issue by ghost** [cssmagic/CSS-Secrets#45]
### 第 125 页 · `span` 标签 `>` 颜色不对

应该为绿色
### 第 186 页 · `left`  颜色不对

应该为玫红色
### 第 187 页 · `transform`  颜色不对

应该为玫红色

**Comment by cssmagic** [comment]
👍 谢谢反馈，确认后会添加到勘误表中。

**Comment by cssmagic** [comment]
已收录到 [“勘误表 - 排版失误”](https://github.com/cssmagic/CSS-Secrets/issues/36) 中。
