### ISSUE TITLE
P10  <input> 标签不支持 ::after, ::before 伪无素

### ISSUE THREAD

**Issue by KAWATAAAAAA** [cssmagic/CSS-Secrets#48]
如题，作为dom元素，伪元素都是在容器内进行渲染的，,input无法容纳元素，第十页图1-8上面的提示框气泡，一看就是input标签所弹出的，而css中写到有：：before，input不会支持，不是特殊的HTML5类型的输入框是不会弹出提示气泡的，而这里有，我感觉不对劲，是我理解错了还是怎么？解决方案，在input上套一个div，给div那个加before，才能实现！然后最后一行的 transform我看不懂，提示气泡为何要让它旋转？，那么这样又与图1-8的显示对不上号了！如果我的评论提交是错误的恳请原谅！如果正确请修正～谢谢

**Comment by cssmagic** [comment]
谢谢反馈。稍后会确认你提到的这个问题。

也欢迎其他读者参与讨论 :smiley:

**Comment by jimyuan** [comment]
楼主理解错误，书上的代码没问题。 .callout 就是指的那个 popup 组件，不是 input；::before 里定义的是那个向上的小箭头。这里 input 元素只是触发该 popup，不参与该组件的构成。

**Comment by cssmagic** [comment]
@jimyuan 
谢谢解答 :+1:
