### ISSUE TITLE
渐变问题

### ISSUE THREAD

**Issue by ggotost** [cssmagic/CSS-Secrets#52]
css揭秘讲背景那一张涉及了很多渐变  里面有3 4 或者更多的渐变色的时候，怎么理解啊，我每次写的时候总写不出来我想要的渐变

**Comment by cssmagic** [comment]
如果单个渐变的色标数量比较多、不好控制的话，可以尝试一些在线工具，可以通过可视化的界面生成代码，应该会适合你。
