### ISSUE TITLE
线性渐变

### ISSUE THREAD

**Issue by YingshanDeng** [cssmagic/CSS-Secrets#53]
@cssmagic 你好，我在使用线性渐变的时候，遇到一个问题，很困惑，大神不知能否解答一下。

```
div {
            width: 200px;
            height: 100px;
            background: -webkit-linear-gradient(left top, blue 50%, red 50%);
        }
<div></div>
```

结果是 ：
![image](https://cloud.githubusercontent.com/assets/7246595/19305795/330eb32e-90a5-11e6-81d6-a1ecfa9af502.png)

但是如果修改为：

```
div {
            width: 200px;
            height: 100px;
            /*background: -webkit-linear-gradient(left top, blue 50%, red 50%);*/
            background: linear-gradient(to right bottom, blue 50%, red 50%);
        }
```

结果却是：
![image](https://cloud.githubusercontent.com/assets/7246595/19305805/4737f3a6-90a5-11e6-8165-e8f81829023a.png)

MDN 上文档说，带有前缀的是旧语法，已经启用，但是实际中还是可以用。这二者是啥区别呢？会导致结果不同，谢谢。:-)

**Comment by nzj19910102** [comment]
你把第一个的top,或者第二个的bottom去掉就可以了

**Comment by cssmagic** [comment]
从草案到定稿的过程中，CSS 属性的语法可能会有变化，或者语法没有变化但行为有变化。为兼容即有代码，浏览器在实现标准的（无前缀的）行为之后，仍然会保留未定稿时期的（加前缀的）行为，于是这两者的行为就不一致了。

谢谢你的提问，我还从未留意过线性渐变的这个行为变化。我稍后会整理到注解中。
