### ISSUE TITLE
关于 “cascade” 一词的译法

### ISSUE THREAD

**Issue by hax** [cssmagic/CSS-Secrets#6]
贴一个09年时我在图灵内部论坛的讨论。此文基于六年前情况，现在没有重新检讨过状况，所以谨供参考。

> 层叠和级联本身并没有什么特别区别，只是对cascade的不同译法。我偏好级联主要有几个原因：
> 1. 层叠这个词对于初学者有点不知所云。最初翻译的人可能是不知道还有级联这种在其他领域已经有的译法可直接拿来用，所以才译为了层叠。
>    我的经验是，很长一段时间以来，我很熟悉CSS，但是就是一直搞不懂层叠这个词到底什么意思。对于这点，可能有人会认为有主观之嫌，最好的方式是去问问那些对网页有些概念，但是并不很了解CSS的人看到层叠这个词做何理解。至于为什么不理解层叠的情况下，层叠的用法甚广，实际上是反正大家很多时候不求甚解，知道这个指代什么就得了。然而进入翻译领域，则不得不刨根问底。
> 2. 层叠这个词主要被用作形容词（许多人更愿意加一个 式 字，以 层叠式 来翻译cascading），而cascade是名词或动词。虽然你总可以强制将层叠作为一个名词或动词看待，但是总归不太自然。而级联则名词、动词、形容词均适用。
> 
> 可对比以下这些说法：
> 
> A和B层叠 vs A和B级联（cascade A and B）
> A和B的层叠 vs A和B的级联（The cascade of A and B）
> 层叠顺序 vs 级联顺序（cascading order）
> 1. 所谓cascade，归根到底是动词性的，即将一些样式表合并起来的过程。所以cascading style sheet之cascading并不是单纯描述若干sheet层叠的状态，或者如何进行叠放，而是强调cascading乃是一种机制，是对各个冲突的css declarations进行选择的机制。
> 
> 例句：
> 
> The key feature is the ability to cascade style information specified in the default (user agent) style sheet, user style sheets, linked style sheets, the document head, and in attributes for the elements forming the document body.
> 
> 核心意思是对样式信息进行cascade
> 对比：
> 对样式信息进行层叠
> 对样式信息进行级联
> 
> 这样可以看到层叠这个词的缺陷：
> 
> 层叠给人的感觉是仍旧是一层一层的、分离的。
> 
> 而级联是将这些东西串接到一起。
> 
> 这是最重要的差别。
> 
> 最后是 级联 这个词在其他领域的用法。
> 
> 主要是两种：
> 
> 一个是物理设备的层次式的连接，比如USB hub就是一个级联的例子。
> 另一个是数据库中的层次关联性操作，比如级联删除。
> 
> 严格的说，在CSS中，基本上是一个串联，而不是一分二、二分四的级联，所以按理说，串接样式表或者串联样式表的译法最为靠谱。
> 
> 但是级联这个词本身，其实只包含 分级 和 联接 的意思，并没有规定一级到二级就要一分n，因此拿来用也并不能算错。
> 
> 而且我们要考虑约定俗成。就这点而言，串联、串接一律淘汰。只剩下级联和层叠是在一个数量级上的。
> 
> 所以最后我建议选择 级联。

**Comment by Justineo** [comment]
级联 +1

**Comment by flyyang** [comment]
级联 +1

**Comment by cssmagic** [comment]
然而我的选择又是跟以上各位不一致的 :scream: ，稍后有空会跟大家详细解释。
