### ISSUE TITLE
渐变棋盘的疑问

### ISSUE THREAD

**Issue by everywill** [cssmagic/CSS-Secrets#64]
书中用的是4个渐变来实现棋盘背景：

>  linear-gradient(45deg, #bbb 25%, transparent 0),
    linear-gradient(45deg, transparent 75%, #bbb 0),
    linear-gradient(45deg, #bbb 25%, transparent 0),
    linear-gradient(45deg, transparent 75%, #bbb 0);

和2个渐变，类似下面：

> linear-gradient(45deg, #6cf 25%, transparent 0, transparent 75%, #6cf 0),
    linear-gradient(45deg, #6cf 25%, transparent 0, transparent 75%, #6cf 0);

感觉上是一样的，结果后者中小正方形对角线没有接上而产生的比较明显的空隙（比前者明显很多），想请教大大是什么原因导致了这样的区别？

**Comment by cssmagic** [comment]
在书中（第 39 页）作者最后也把代码简化成了两层渐变图案。理论上来说，这两种方案的效果应该没有区别，但也不排除浏览器在实际渲染中出现差异。

说到缝隙，最根本的原因在于，CSS 描述的是矢量信息，而浏览器需要以位图的方式把渲染效果显示出来，因为显示设备都是基于像素的。矢量信息在整个渲染过程中的哪个环节转换为位图信息，决定了最终渲染效果的误差有多少。理论上来说，矢量信息越晚转换为位图，渲染效果越精确，但计算也越复杂或越难做到。

具体到这个例子，由于这种斜向渐变的渲染结果不可能是对齐到像素的位图，在斜边拼接的地方很容易产生缝隙。

总的来说，本节的重心在于呈现思维方式。如果你真的要实现一个棋盘图案，还是选择其它更稳定的方案为上。
