### ISSUE TITLE
第7章结构与布局章节例子的疑问

### ISSUE THREAD

**Issue by everywill** [cssmagic/CSS-Secrets#69]
这一章的第一个例子(自适应内部元素)，在给出解决方案之前有一个使用float来尝试的例子：

例子中图片下方的文字发生折行，float的元素最后的宽度是图片的宽度，但在safari firefox和chrome里尝试的时候都没有得到这样的结果，文字并没有发生折行。

[css2.1 spec](https://www.w3.org/TR/2011/REC-CSS2-20110607/visudet.html#float-width)里说floating non-replaced的元素的宽度是min(max(preferred minimum width, available width), preferred width)， preferred width是考虑所有显式换行之后的宽度；书中的例子中折行的地方似乎有一个回车换行，但在我的尝试里在个浏览器中似乎并没有把它识别为显式换行，因此最后表现为没有换行。

请问这个这个使用float的例子是有误吗，以及想问魔法哥知道什么可以作为显式换行吗？
谢谢魔法哥！

**Comment by cssmagic** [comment]
因为只有文字叙述，我不确定我是否理解了你的问题。我先尝试简单地回答一个小疑问：

> 书中的例子中折行的地方似乎有一个回车换行，但在我的尝试里在个浏览器中似乎并没有把它识别为显式换行，因此最后表现为没有换行。

在默认情况下，HTML 源码中的换行符和其它空白符（空格、tab）一样，在渲染时只会呈现出一个空格。如果需要做到 “显式换行”，要么插入 `<br>` 标签，要么对元素应用 `white-space: pre` 等 CSS 样式。
