### ISSUE TITLE
线性渐变

### ISSUE THREAD

**Issue by shimuash** [cssmagic/CSS-Secrets#75]
您好好，我在body上直接设置线性渐变背景，body元素里面没有添加任何东西。

`body {
	background: linear-gradient(#fb3, #58a);
}`

产生下面结果，

![body](https://cloud.githubusercontent.com/assets/19681723/24297947/78028c34-10df-11e7-8500-b91dfdafebeb.png)

为什么不是下面这种效果？是有默认的background-size？

![body2](https://cloud.githubusercontent.com/assets/19681723/24298440/f87eaab8-10e0-11e7-9ff8-ffe80a48b746.png)

**Comment by cssmagic** [comment]
我写了个 Demo，相信你可以看出关键因素：
http://codepen.io/cssmagic/pen/WpgbZr

**Comment by shimuash** [comment]
@cssmagic 好的，谢谢。
