### ISSUE TITLE
第59页勘误

### ISSUE THREAD

**Issue by sanqianwdj** [cssmagic/CSS-Secrets#76]
代码部分  transform: skew(45deg);  应该改为  transform: skew(-45deg);

**Comment by cssmagic** [comment]
谢谢反馈！

稍后会确认并添加到勘误表中。

**Comment by cssmagic** [comment]
❤️ 已收入 [“中文版勘误表”](https://github.com/cssmagic/CSS-Secrets/issues/2)，谢谢反馈！
