### ISSUE TITLE
fill="%23fb3”，%23fb3怎么理解?fb3是颜色，23是什么？

### ISSUE THREAD

**Issue by nanyangyeren** [cssmagic/CSS-Secrets#84]
你好，正在拜读大作css secret的 drop shadows，碰到一个问题，下边的“fill="%23fb3”，%23fb3表示什么意思？百思不得其解，🙏。
.cutout {
border: 1.0em solid #58a;
border-image: 1 url('data:image/svg+xml,
<svg xmlns="http://www.w3.org/2000/svg"\
width="3" height="3" fill="%23fb3">

');
background-clip: padding-box;
}

**Comment by yonjar** [comment]
%23 : #

**Comment by nanyangyeren** [comment]
跪谢跪谢！！！

**Comment by cssmagic** [comment]
在微信公众号里也看到了你的提问，已回复了：

> 这段 SVG 代码是以 Data URI 的形式写入 CSS 的，因此 URL 中的 `#` 字符被编码成 `%23` 了。
