### ISSUE TITLE
网站挂了，会修一下吗

### ISSUE THREAD

**Issue by tianzhich** [cssmagic/CSS-Secrets#89]
如题

**Comment by cssmagic** [comment]
你好，谢谢反馈。

你说的是 `book.cssmagic.net` 这个域名不能访问对吧？这个域名确实已经下线了。

这个域名其实只是指向本 repo 的一个快捷方式，并不是一个独立网站，所以域名下线并不会产生任何功能缺失。我已经把这个域名从本 repo 的官网链接字段去掉了，以免误导更多人。

**Comment by tianzhich** [comment]
感谢！

**Comment by cssmagic** [comment]
我突然想起来书中的 “译者序” 留了 `http://book.cssmagic.net/` 这个网址，汗颜。

已把这个域名恢复了。给大家带来的不便深表歉意 😳
